version: '2.0'
services:
  mysql_db:
    image: mysql
    ports:
      - '3308:3306'
    expose:
      - '3306'
    environment:
      MYSQL_DATABASE: yt_metadata
      MYSQL_ROOT_PASSWORD: root

  spring_api_service:
    build:
      context: demo-app-backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - mysql_db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_db:3306/yt_metadata?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

  react_service:
    build:
      context: demo-app-frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
   
